version: "3.7"
services:
  backend:
    build: ./backend/
    #image: postgres:12-alpine
    volumes:
    #  - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    #networks:
    #  - backend
    ports:
      - "5432:5432"
    #environment:
    #  POSTGRES_DB: pollsdb
    #  POSTGRES_USER: polls
    #  POSTGRES_PASSWORD: yZnaaX4ZeIeVdahDedQQ
    restart: always
    init: true
    #command: localedef -i ru_RU -c -f UTF-8 -A /usr/share/locale/locale.alias ru_RU.UTF-8
  frontend:
    build: ./frontend/
      #context: .
    depends_on:
      - backend
    #networks:
    #  - frontend
    ports:
      - "8080:8080"
    #restart: always
#networks:
#  frontend:
#  backend:
volumes:
  db-data:
